In [1]:
import pandas as pd

## Reading Data

In [2]:
df= pd.read_csv('data.csv')

In [3]:
df.head()

fever  bodyPain  age  runnyNose  diffBreath  infectionProb
0   98.338324         0   82          1           1              1
1   99.968366         0   86          1          -1              0
2   98.542013         1    1          1          -1              0
3  101.695911         1   28          0          -1              0
4  101.627213         0   14          0           0              1

In [4]:
df.tail()

fever  bodyPain  age  runnyNose  diffBreath  infectionProb
2570  101.332158         0    6          0           0              1
2571  101.414272         0   38          1           0              1
2572  100.324562         0   10          1          -1              1
2573  101.789890         0   61          1           1              1
2574  100.076689         1   72          1           1              0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2575 entries, 0 to 2574
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   fever          2575 non-null   float64
 1   bodyPain       2575 non-null   int64  
 2   age            2575 non-null   int64  
 3   runnyNose      2575 non-null   int64  
 4   diffBreath     2575 non-null   int64  
 5   infectionProb  2575 non-null   int64  
dtypes: float64(1), int64(5)
memory usage: 120.8 KB


In [6]:
df['diffBreath'].value_counts()

 1    867
 0    857
-1    851
Name: diffBreath, dtype: int64

In [7]:
df.describe()

fever     bodyPain          age    runnyNose   diffBreath  \
count  2575.000000  2575.000000  2575.000000  2575.000000  2575.000000   
mean    100.013330     0.482330    50.647379     0.514175     0.006214   
std       1.157088     0.499785    28.642044     0.499896     0.816949   
min      98.002429     0.000000     1.000000     0.000000    -1.000000   
25%      99.014622     0.000000    25.000000     0.000000    -1.000000   
50%     100.022205     0.000000    52.000000     1.000000     0.000000   
75%     101.006176     1.000000    75.000000     1.000000     1.000000   
max     101.998339     1.000000   100.000000     1.000000     1.000000   

       infectionProb  
count    2575.000000  
mean        0.493204  
std         0.500051  
min         0.000000  
25%         0.000000  
50%         0.000000  
75%         1.000000  
max         1.000000

## Train TEST split<br>
we do this because sbse phale training karein and phir bad me test kare ki hamara jo data hai wo kitne % accuracy de raha hai.
## iloc
Python iloc() function enables us to select a particular cell of the dataset, that is, it helps us select a value that belongs to a particular row or column from a set of values of a data frame or dataset.

In [8]:
import numpy as np

In [9]:
def data_split(data,ratio):
    np.random.seed(42) # it freeze the data
    shuffled= np.random.permutation(len(data)) #it will give list of permutaiton (0 to len(data)-1)
    test_set_size= int(len(data)*ratio)  # it will give quantity of data that you want.
    test_indices = shuffled[:test_set_size] #this will take those value which are present in test_set_size
    train_indices= shuffled[test_set_size:]  # this will take remaining value of your data.csv

    return data.iloc[train_indices],data.iloc[test_indices]

In [10]:
np.random.permutation(9)

array([5, 7, 0, 8, 4, 2, 6, 3, 1])

In [11]:
train,test= data_split(df, 0.2)

In [12]:
train

fever  bodyPain  age  runnyNose  diffBreath  infectionProb
1703  101.286387         0   32          0           0              0
1675  100.413832         0    6          1           0              1
1518  101.713812         1   65          1           0              1
361   101.890224         0   40          1          -1              0
1544   98.106949         1   22          1           1              0
...          ...       ...  ...        ...         ...            ...
1638  101.696947         1   67          0           0              0
1095  100.949951         1   93          0           0              0
1130   98.844061         0   67          1           1              1
1294  100.605883         1   78          0           0              0
860    99.035060         1    1          1           1              0

[2060 rows x 6 columns]

In [13]:
test

fever  bodyPain  age  runnyNose  diffBreath  infectionProb
1644   99.422863         1   74          1          -1              0
1189  101.256009         1   84          0          -1              1
495   101.569834         1   10          1           0              1
1656   99.091086         0   13          1           0              0
651    99.869715         0   49          0           0              0
...          ...       ...  ...        ...         ...            ...
1627  100.748007         0   68          1          -1              0
471    98.496286         0   14          0          -1              1
700   101.810469         0   25          0           1              1
25     99.067594         0   96          1           1              1
755   101.266240         0   91          1           1              0

[515 rows x 6 columns]

In [14]:
X_train = train[['fever','bodyPain',"age","runnyNose",'diffBreath']].to_numpy() #it will give siliced dataframe of train dataset.
X_test = test[['fever','bodyPain',"age","runnyNose",'diffBreath']].to_numpy() #it will give siliced dataframe of test dataset.


In [15]:
Y_train = train[['infectionProb']].to_numpy().reshape(2060,) #it will give siliced dataframe of train dataset. only infection column included.
Y_test = test[['infectionProb']].to_numpy().reshape(515,) #it will give siliced dataframe of test dataset. only infection column included.

In [16]:
Y_train

array([0, 1, 1, ..., 1, 0, 0], dtype=int64)

# WE USE --->LOGISTIC ALGORITHM<-------

for train machine learining model.

In [17]:
from sklearn.linear_model import LogisticRegression

In [18]:
clf= LogisticRegression()
clf.fit(X_train,Y_train)

LogisticRegression()

# we use predict()
This will give value of infection in 0 or 1

In [19]:
clf.predict([[100,1,22,1,1]])

array([0], dtype=int64)

But we want probablity <br>
so we use,probafunction

In [20]:
clf.predict_proba([[100,1,22,1,1]])

array([[0.52231105, 0.47768895]])

it showw probablity of 0.47768 hone ki probality

In [23]:
inputFeature=[99,0,90,-1,1]
infProb= clf.predict_proba([[100,1,22,1,1]])[0][1]

In [24]:
infProb

0.47768894618218655